spring.application.name=CASA_Legal_Hub_management_system

# Database - Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-steep-credit-aqw1sksb-pooler.c-8.us-east-1.aws.neon.tech/CASA_Legal_Hub?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_FwUIcv6WBYm0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Port
server.port=${PORT:8080}
