spring.application.name=CASA_Legal_Hub_management_system

# DATABASE (RENDER POSTGRES)
spring.datasource.url=jdbc:postgresql://dpg-d8ihpc67r5hc73cu67vg-a.oregon-postgres.render.com:5432/casa_legal_hub_db_l6vs

spring.datasource.username=casa_legal_hub_db_l6vs_user
spring.datasource.password=UAHjcjpLW5pJdLuCRRUXhG0mB98zBVZ1

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
file.upload-dir=uploads

# EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# RENDER PORT
server.port=${PORT:8080}
