spring.application.name=CASA_Legal_Hub_management_system

# DATABASE (RENDER POSTGRES)
spring.datasource.url=postgresql://casa_legal_hub_db_user:qh2HR2SkNuBs3FgVfcKPIzCH3gatJGHf@dpg-d85d5fugvqtc73bo2vug-a.oregon-postgres.render.com/casa_legal_hub_db
spring.datasource.username=casa_legal_hub_db_user
spring.datasource.password=qh2HR2SkNuBs3FgVfcKPIzCH3gatJGHf

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# FILE UPLOAD
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
file.upload-dir=uploads

# EMAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# RENDER PORT
server.port=${PORT:8080}